apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    headerStyle: boxedWidgets
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system.svc.cluster.local
    useEqualHeights: true
    target: _self
    statusStyle: dot
    layout:
      System:
        tab: Core
        style: row
        columns: 4
      Monitoring:
        tab: Core
        style: row
        columns: 4
      Media:
        tab: Media
        style: row
        columns: 4
      Services:
        tab: Services
        style: row
        columns: 4
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: true
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: long
  kubernetes.yaml: |
    mode: cluster
    ingress: true
  bookmarks.yaml: ""
  services.yaml: |
    # TODO: add headlamp, kubewall and weave-gitops
    - System:
      - Traefik:
          href: https://traefik.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://traefik-api.traefik.svc.cluster.local:8080
          icon: traefik.svg
          description: Reverse proxy
          widget:
            type: traefik
            url: http://traefik-api.traefik.svc.cluster.local:8080
      - Longhorn:
          href: https://longhorn.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://longhorn-frontend.longhorn-system.svc.cluster.local
          icon: longhorn.svg
          description: Clustered storage
      - Authentik:
          href: https://authentik.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://authentik-server.authentik.svc.cluster.local
          icon: authentik.png
          description: Authentication management
          widget:
            type: authentik
            url: http://authentik-server.authentik.svc.cluster.local
            key: "{{HOMEPAGE_VAR_AUTHENTIK_API_KEY}}"
      - Portainer:
          href: https://portainer.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://portainer.portainer.svc.cluster.local:9000
          icon: portainer.svg
          description: Container management
      - Garage:
          href: https://garage.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://garage.garage.svc.cluster.local:3909
          icon: garage.svg
          description: Object storage
      - Crowdsec:
          href: https://crowdsec.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://crowdsec-service.crowdsec.svc.cluster.local:3000
          icon: crowdsec.svg
          description: Threat intelligence
          widget:
            type: crowdsec
            url: http://crowdsec-service.crowdsec.svc.cluster.local:8080
            username: crowdsec-lapi
            password: "{{HOMEPAGE_VAR_CROWDSEC_LAPI_KEY}}"
      - Goldilocks:
          href: https://goldilocks.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://goldilocks-dashboard.goldilocks.svc.cluster.local
          icon: mdi-memory
          description: Kubernetes resource recommendations
    - Monitoring:
      - Prometheus:
          href: https://prometheus.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          icon: prometheus.svg
          description: Monitoring and alerts
          widget:
            type: prometheus
            fields: ["targets_up", "targets_down", "targets_total"]
            url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
      - Grafana:
          href: https://grafana.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local
          icon: grafana.svg
          description: Data visualization
          widget:
            type: grafana
            url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local
            username: "{{HOMEPAGE_VAR_GRAFANA_USERNAME}}"
            password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"
      - ntfy:
          href: https://ntfy.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://ntfy.ntfy.svc.cluster.local
          icon: ntfy.svg
          description: Notifications
          widget:
            type: customapi
            url: http://ntfy.ntfy.svc.cluster.local/v1/stats
            mappings:
              - field: messages
                label: Messages
                format: number
              - field: messages_rate
                label: Messages/s
                format: number
    - Media:
      - Jellyfin:
          href: https://jellyfin.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://jellyfin.jellyfin.svc.cluster.local:8096
          icon: jellyfin.svg
          description: Media library
          widget:
            type: jellyfin
            url: http://jellyfin.jellyfin.svc.cluster.local:8096
            key: "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}"
            enableBlocks: true
            enableUser: true
            showEpisodeNumber: true
      - Navidrome:
          href: https://navidrome.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://navidrome.navidrome.svc.cluster.local:4533
          icon: navidrome.svg
          description: Music library
          widget:
            type: navidrome
            url: http://navidrome.navidrome.svc.cluster.local:4533
            user: "{{HOMEPAGE_VAR_NAVIDROME_USER}}"
            token: "{{HOMEPAGE_VAR_NAVIDROME_TOKEN}}"
            salt: "{{HOMEPAGE_VAR_NAVIDROME_SALT}}"
      - AudioBookShelf:
          href: https://audiobookshelf.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://audiobookshelf.audiobookshelf.svc.cluster.local:13378
          icon: audiobookshelf.svg
          description: Books and audiobooks
          widget:
            type: audiobookshelf
            url: http://audiobookshelf.audiobookshelf.svc.cluster.local:13378
            key: "{{HOMEPAGE_VAR_AUDIOBOOKSHELF_API_KEY}}"
    - Services:
      - Linkwarden:
          href: https://linkwarden.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://linkwarden.linkwarden.svc.cluster.local:3000
          icon: linkwarden.png
          description: Bookmark management
          widget:
            type: linkwarden
            url: http://linkwarden.linkwarden.svc.cluster.local:3000
            key: "{{HOMEPAGE_VAR_LINKWARDEN_API_KEY}}"
      - Karakeep:
          href: https://karakeep.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://karakeep.karakeep.svc.cluster.local:3000
          icon: karakeep.svg
          description: Bookmark anything and everything
          widget:
            type: karakeep
            url: http://karakeep.karakeep.svc.cluster.local:3000
            key: "{{HOMEPAGE_VAR_KARAKEEP_API_KEY}}"
      - Vaultwarden:
          href: https://vaultwarden.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://vaultwarden.vaultwarden.svc.cluster.local
          icon: vaultwarden.svg
          description: Password manager
      - Nextcloud:
          href: https://nextcloud.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://nextcloud.nextcloud.svc.cluster.local:8080
          icon: nextcloud.svg
          description: Cloud storage
          widget:
            type: nextcloud
            url: https://nextcloud.${ROOT_DOMAIN}
            key: "{{HOMEPAGE_VAR_NEXTCLOUD_API_KEY}}"
      - Home Assistant:
          href: https://home-assistant.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://home-assistant.home-assistant.svc.cluster.local:8080
          icon: home-assistant.svg
          description: Home automation
          widget:
            type: homeassistant
            url: http://home-assistant.home-assistant.svc.cluster.local:8080
            key: "{{HOMEPAGE_VAR_HOME_ASSISTANT_API_KEY}}"
      - PiHole:
          href: https://pihole.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://pihole-web.pihole.svc.cluster.local
          icon: pi-hole.svg
          description: DNS
          widget:
            type: pihole
            url: http://pihole-web.pihole.svc.cluster.local
            version: 6
            key: "{{HOMEPAGE_VAR_PIHOLE_PASSWORD}}"
      - Gitea:
          href: https://gitea.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://gitea-http.gitea.svc.cluster.local:3000
          icon: gitea.svg
          description: Git server
          widget:
            type: gitea
            url: http://gitea-http.gitea.svc.cluster.local:3000
            key: "{{HOMEPAGE_VAR_GITEA_API_KEY}}"
      - Immich:
          href: https://immich.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://immich-server.immich.svc.cluster.local:2283
          icon: immich.svg
          description: Photos and videos
          widget:
            type: immich
            url: http://immich-server.immich.svc.cluster.local:2283
            key: "{{HOMEPAGE_VAR_IMMICH_API_KEY}}"
            version: 2
      - FreshRSS:
          href: https://freshrss.${LOCAL_ROOT_DOMAIN}
          siteMonitor: http://freshrss.freshrss.svc.cluster.local:80
          icon: freshrss.svg
          description: RSS News Reader
          widget:
            type: freshrss
            url: http://freshrss.freshrss.svc.cluster.local:80
            username: "{{HOMEPAGE_VAR_FRESHRSS_USERNAME}}"
            password: "{{HOMEPAGE_VAR_FRESHRSS_PASSWORD}}"
