- name: "Bootstrap new user, admin permissions and ssh keys on mini pcs"
  hosts: mini_pcs
  become: true
  # become_method: su
  become_flags: "-"
  tags: [bootstrap, never]

  # TODO: hacky workaround for become_method not taking precedence over
  # ansible_become_method specified in inventory
  vars:
    ansible_become_method: su

  roles:
    - role: user
      tags: [user]
    - role: sudo
      tags: [sudo]
    - role: sshkey
      tags: [sshkey]


- name: "Apply common configurations across all nodes"
  hosts: k8s_cluster
  become: true

  roles:
    - role: common-packages
      tags: [common, packages]
    - role: sshd
      tags: [ssh, sshd]
    - role: timezone
      tags: [timezone, tz]
    - role: disable-swap
      tags: [disable-swap, swap]
    - role: longhorn-packages
      tags: [longhorn, packages]
    - role: network-tuning
      tags: [network-tuning]

- name: "Configure mini pcs"
  hosts: mini_pcs
  become: true

  roles:
   - role: mini-pc/inotify
     tags: inotify

- name: "Configure pis"
  hosts: pis
  become: true

  roles:
    - role: pi/kernel8
      tags: kernel8
    - role: pi/disable-wifi
      tags: disable-wifi
    - role: pi/cgroup
      tags: cgroup


- name: "Install k3s, helm, velero, longhornctl and flux on first master node"
  hosts: k8s_first_master_node
  become: true

  roles:
    - role: k3s
      tags: k3s
    - role: helm
      tags: helm
    - role: velero-cli
      tags: velero-cli
    - role: longhorn-cli
      tags: longhorn-cli
    - role: flux/cli
      tags:
        - flux
        - flux-cli

- name: "Install k3s on rest of masters and worker nodes"
  hosts: k8s_master_nodes,k8s_worker_nodes
  become: true
  gather_facts: true

  roles:
    - role: k3s
      tags: k3s


- name: "Setup tailscale on all nodes"
  hosts: k8s_cluster
  become: true

  roles:
    - role: tailscale
      tags: tailscale

- name: "Bootstrap flux"
  hosts: k8s_first_master_node
  become: true
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  roles:
    - role: flux/bootstrap
      tags:
        - flux
        - flux-bootstrap

