apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-operator
  namespace: monitoring
spec:
  chart:
    spec:
      chart: fluent-operator
      version: 3.5.0
      sourceRef:
        kind: HelmRepository
        name: fluent
      interval: 5m
  releaseName: fluent-operator
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    containerRuntime: containerd
    operator:
      resources:
        limits:
          memory: 256Mi
    fluentbit:
      resources:
        limits:
          memory: 600Mi
      input:
        tail:
          multilineParser: "docker, cri"
        fluentBitMetrics:
          scrapeInterval: "2"
          scrapeOnStart: true
          tag: "fb.metrics"
      output:
        loki:
          enable: true
          host: loki.monitoring.svc.cluster.local
          autoKubernetesLabels: on
          # needed for dashboards to work
          labels:
            - "container=$kubernetes['container_name']"
            - "namespace=$kubernetes['namespace_name']"
            - "pod=$kubernetes['pod_name']"
        prometheusMetricsExporter:
          match: "fb.metrics"
          metricsExporter:
            host: "0.0.0.0"
            port: 2020
            addLabels:
              app: "fluentbit"
      filter:
        multiline:
          enable: true
        containerd:
          enable: false
