apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-linkwarden
  namespace: linkwarden
spec:
  chart:
    spec:
      chart: cluster
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
      interval: 5m
  releaseName: cnpg-linkwarden
  valuesFrom:
    - kind: Secret
      name: cnpg-backup-values
  values:
    version:
      postgresql: "16"
    cluster:
      instances: 1
      storage:
        size: 8Gi
      walStorage:
        enabled: true
        size: 1Gi
      monitoring:
        enabled: true
        prometheusRule:
          enabled: true
      additionalLabels:
        release: kube-prometheus-stack
      superuserSecret: cnpg-superuser-secret
    backups:
      enabled: true
      s3:
        bucket: cnpg
      wal:
        encryption: ""
      dats:
        encryption: ""
      scheduledBackups:
        - name: daily-backup
          schedule: "0 0 0 * * *"
