argument_specs:
  main:
    options:
      borgmatic_config:
        type: "dict"
        required: true
      borgmatic_config_private:
        type: "dict"
        required: false
        default: {}
      borg_server_host:
        type: "str"
        required: false
        default: null
