argument_specs:
  main:
    options:
      borgmatic_config_group:
        type: "dict"
        required: false
        default: {}
      borgmatic_config_group_private:
        type: "dict"
        required: false
        default: {}
      borgmatic_config:
        type: "dict"
        required: false
        default: {}
      borgmatic_config_private:
        type: "dict"
        required: false
        default: {}
      borg_server_host:
        type: "str"
        required: false
        default: null
      borgmatic_scripts:
        type: dict
        required: false
        default: {}
      borgmatic_do_restore:
        type: bool
        required: false
        default: false
      borgmatic_restore_archive:
        type: str
        required: false
        default: latest
      borgmatic_restore_dest:
        type: str
        required: false
        default: /tmp
      borgmatic_restore_paths:
        type: list
        elements: str
        required: false
        default: []
      borgmatic_restore_all_paths:
        type: bool
        required: false
        default: false
      borgmatic_restore_databases:
        type: list
        elements: str
        required: false
        default: []
      borgmatic_restore_all_databases:
        type: bool
        required: false
        default: false
