apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-talk-hpb
  namespace: nextcloud
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginList:
      - "*"
