argument_specs:
  main:
    options:
      technitium_version:
        type: str
        required: true
      technitium_env:
        type: dict
        required: false
        default: {}
      technitium_env_private:
        type: dict
        required: false
        default: {}
      root_domain:
        type: str
        required: true
      technitium_cluster_zone:
        type: str
        required: true
