apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-tailscale-proxy-data
  namespace: traefik
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
