apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      version: 2025.8.1
      sourceRef:
        kind: HelmRepository
        name: authentik
      interval: 5m
  releaseName: authentik
  valuesFrom:
    - kind: Secret
      name: authentik-values
  values:
    authentik:
      postgresql:
        host: cnpg-authentik-cluster-rw.authentik.svc.cluster.local
    server:
      ingress:
        ingressClassName: traefik
        enabled: true
        hosts:
          - authentik.${LOCAL_ROOT_DOMAIN}
          - authentik.${ROOT_DOMAIN}
      resources:
        limits:
          memory: 1Gi
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          labels:
            release: kube-prometheus-stack
    worker:
      resources:
        limits:
          memory: 1Gi
    prometheus:
      rules:
        enabled: true
        labels:
          release: kube-prometheus-stack
    postgresql:
      enabled: false
    redis:
      enabled: true
