- name: "apt: Update"
  ansible.builtin.apt:
    update_cache: yes

- name: "apt: Upgrade"
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: "Check /var/run/reboot-required"
  ansible.builtin.stat:
    path: "/var/run/reboot-required"
    get_checksum: false
  register: var_run_reboot_required

- name: "Reboot if needed"
  ansible.builtin.reboot:
  when: var_run_reboot_required.stat.exists
