apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  chart:
    spec:
      chart: descheduler
      version: 0.35.1
      sourceRef:
        kind: HelmRepository
        name: descheduler
      interval: 5m
  releaseName: descheduler
  values:
    schedule: "*/10 * * * *"
    deschedulerPolicy:
      metricsProviders:
        - source: "KubernetesMetrics"
      profiles:
        - name: default
          pluginConfig:
            - name: RemoveDuplicates
            - name: RemovePodsViolatingInterPodAntiAffinity
            - name: RemovePodsViolatingNodeAffinity
              args:
                nodeAffinityType:
                  - requiredDuringSchedulingIgnoredDuringExecution
            - name: RemovePodsHavingTooManyRestarts
              args:
                podRestartThreshold: 100
                includingInitContainers: true
            - name: LowNodeUtilization
              args:
                metricsUtilization:
                  source: "KubernetesMetrics"
                thresholds:
                  memory: 20
                targetThresholds:
                  memory: 70
            - name: PodLifeTime
              args:
                maxPodLifeTimeSeconds: 86400
                states:
                  - "Pending"
                  - "Unknown"
                  - "NodeLost"
                  - "UnexpectedAdmissionError"
                  - "PodInitializing"
                  - "ContainerCreating"
                  - "ImagePullBackOff"
                  - "CrashLoopBackOff"
                  - "CreateContainerConfigError"
                  - "ErrImagePull"
                  - "ImagePullBackOff"
                  - "CreateContainerError"
                  - "InvalidImageName"
                includingInitContainers: true
          plugins:
            balance:
              enabled:
                - RemoveDuplicates
                - LowNodeUtilization
            deschedule:
              enabled:
                - RemovePodsViolatingInterPodAntiAffinity
                - RemovePodsViolatingNodeAffinity
                - RemovePodsHavingTooManyRestarts
                - PodLifeTime
