apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: test
    namespace: default
    literals:
      - foo=${TIMEZONE}
      - bar=${LOCAL_ROOT_DOMAIN}
generatorOptions:
  disableNameSuffixHash: true
resources: []
