apiVersion: v1
kind: Pod
metadata:
  name: podinfo
  namespace: default
spec:
  containers:
    - name: podinfo
      image: ghcr.io/stefanprodan/podinfo:latest
      env:
        - name: TIMEZONE
          value: ${TIMEZONE}
        - name: LOCAL_ROOT_DOMAIN
          value: ${LOCAL_ROOT_DOMAIN}
