- name: "Gather facts for borg backup server"
  hosts: debian_vps
  tags: [borg-backup, borg, backup]

- name: "Bootstrap new user, admin permissions and ssh keys on openbsd VPS"
  hosts: openbsd_vps
  become: true
  # become_method: su
  become_flags: "-"
  tags: [bootstrap, never]

  # TODO: hacky workaround for become_method not taking precedence over
  # ansible_become_method specified in inventory
  vars:
    ansible_become_method: su

  roles:
    - role: user
      tags: [user]
    - role: doas
      tags: [doas]
    - role: sshkey
      tags: [sshkey]


- name: Configure
  hosts: openbsd_vps
  become: true

  roles:
    - role: sshd
      tags: [ssh, sshd]
    - role: common-packages
      tags: [common, packages]
    - role: borg-backup
      tags: [borg-backup, borg, backup]
    - role: crowdsec
      tags: [crowdsec]
    - role: headscale
      tags: headscale
    - role: acme
      tags: acme
    - role: nginx
      tags: nginx
