apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reflector
  namespace: kube-system
spec:
  path: ./kubernetes/apps/kube-system/reflector
  targetNamespace: kube-system