apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 150Gi
  storageClassName: truenas-smb
