apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  chart:
    spec:
      chart: immich
      version: 0.11.1
      sourceRef:
        kind: HelmRepository
        name: immich
      interval: 5m
  releaseName: immich
  valuesFrom:
    - kind: Secret
      name: immich-values
  values:
    controllers:
      main:
        containers:
          main:
            env:
              IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning.immich.svc.cluster.local:3003"
              DB_HOSTNAME: cnpg-immich-cluster-rw.immich.svc.cluster.local:5432
              DB_USERNAME: immich
              DB_DATABASE_NAME: immich
              VIPS_NOVECTOR: 1
            resources:
              limits:
                gpu.intel.com/i915: 1
            probes:
              liveness:
                enabled: true
                spec:
                  failureThreshold: 120
              readiness:
                enabled: true
                spec:
                  failureThreshold: 120
              startup:
                enabled: true
                spec:
                  failureThreshold: 120
    immich:
      persistence:
        # TODO: remove? since using external libraries anyway
        library:
          existingClaim: immich
    valkey:
      enabled: true
      persistence:
        data:
          enabled: true
          size: 1Gi
          type: persistentVolumeClaim
          storageClass: longhorn
    server:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-server
                tag: v2.7.4
      persistence:
        nextcloud:
          existingClaim: nextcloud
          readOnly: true
      ingress:
        main:
          enabled: true
          hosts:
            - host: immich.${LOCAL_ROOT_DOMAIN}
              paths:
                - path: "/"
                  service:
                    identifier: main
            - host: immich.${ROOT_DOMAIN}
              paths:
                - path: "/"
                  service:
                    identifier: main
    machine-learning:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-machine-learning
                tag: v2.7.4-openvino
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: persistentVolumeClaim
          storageClass: longhorn
