apiVersion: v1
kind: Service
metadata:
  name: traefik-api
  namespace: traefik
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-traefik
  ports:
  - port: 8080
    name: traefik
    targetPort: 8080
    protocol: TCP
