apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      version: 37.1.1
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 5m
  releaseName: traefik
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: longhorn  # TODO: stateful reverse proxy?! might not be ideal
      namespace: longhorn-system
  values:
    priorityClassName: "system-cluster-critical"  # inherited from k3s HelmChart
    deployment:
      additionalContainers:
      - name: ts-sidecar
        imagePullPolicy: Always
        image: "ghcr.io/tailscale/tailscale:v1.88.3"
        env:
        - name: TS_HOSTNAME
          value: ts-sidecar
        - name: TS_KUBE_SECRET
          value: ""
        - name: TS_AUTH_ONCE
          value: "true"
        - name: TS_USERSPACE
          value: "false"
        - name: TS_DEBUG_FIREWALL_MODE
          value: auto
        - name: TS_STATE_DIR
          value: /tailscale
        envFrom:
          - secretRef:
              name: traefik-ts-sidecar-secret
        securityContext:
          privileged: true
        volumeMounts:
          - name: ts-sidecar-data
            mountPath: /tailscale
      additionalVolumes:
        - name: ts-sidecar-data
          persistentVolumeClaim:
            claimName: ts-sidecar-data
    metrics:
      addInternals: true
      prometheus:
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: kube-prometheus-stack
        prometheusRule:
          enabled: true
          rules:
            - alert: TraefikDown
              expr: up{job="traefik"} == 0
              for: 5m
              labels:
                context: traefik
                severity: warning
              annotations:
                summary: "Traefik Down"
                description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"
          additionalLabels:
            release: kube-prometheus-stack
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
      kubernetesIngress:
        publishedService:
          enabled: true
        allowExternalNameServices: true
    service:
      ipFamilyPolicy: "PreferDualStack"
      spec:
        loadBalancerIP: "${TRAEFIK_IP}"
        externalTrafficPolicy: Local
    # TODO: figure out how to get ts-sidecar to run with stricter permissions
    podSecurityContext:
      runAsNonRoot: false
      runAsGroup: 0
      runAsUser: 0
    ports:
      web:
        port: 80
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        port: 443
        forwardedHeaders:
          trustedIPs:
            - "${PROXY_VPS_TAILSCALE_IP}"
            - "${PROXY_VPS_IP}"
        middlewares:
          - crowdsec-bouncer@kubernetescrd
    tlsStore:
      default:
        defaultCertificate:
          secretName: pb4162-dev-tls
    global:
      sendAnonymousUsage: false
    additionalArguments:
      - "--api.insecure=true"
    logs:
      access:
        enabled: true
        format: common
        fields:
          headers: 
            defaultmode: keep
    experimental:
      plugins:
        bouncer:
          moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
          version: "v1.3.5"
