apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-default-values
  namespace: cnpg-system
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: linkwarden,gitea
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
data:
  values.yaml: |
    cluster:
      instances: 1
      monitoring:
        enabled: true
        prometheusRule:
          enabled: true
      additionalLabels:
        release: kube-prometheus-stack
      superuserSecret: cnpg-superuser-secret
    backups:
      enabled: true
      s3:
        bucket: cnpg
      wal:
        encryption: ""
      dats:
        encryption: ""
