apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-default-values
  namespace: cnpg-system
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: linkwarden,gitea,nextcloud,authentik,immich
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
data:
  values.yaml: |
    cluster:
      instances: 1
      monitoring:
        enabled: true
        podMonitor:
          enabled: true
          labels:
            release: kube-prometheus-stack
        prometheusRule:
          enabled: true
          excludeRules:
            - CNPGClusterHACritical
            - CNPGClusterHAWarning
      superuserSecret: cnpg-superuser-secret
    backups:
      enabled: true
      wal:
        maxParallel: 8
      s3:
        bucket: cnpg
      wal:
        encryption: ""
      data:
        encryption: ""
