argument_specs:
  main:
    options:
      registry_base_dir:
        type: str
        required: true
      registry_version:
        type: str
        required: true
      registry_ui_version:
        type: str
        required: true
      registry_users:
        type: list
        elements: str
        required: true
      root_domain:
        type: str
        required: true
