apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
    - ${TRAEFIK_IP}/32
    - ${PIHOLE_IP}/32
    - ${NEXTCLOUD_TALK_HPB_IP}/32
    - ${TRAEFIK_TAILSCALE_PROXY_IP}/32
