apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
    release: kube-prometheus-stack
  name: memory-alerting
  namespace: monitoring
spec:
  groups:
  - name: oomkills
    rules:
      - alert: OomKillEvents
        annotations:
          description: "The pod {{ $labels.pod }} in {{ $labels.namespace }} was recently OOMkilled."
          summary: Pod was OOMKilled
        expr: sum by(namespace, pod) (kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}) > 0
        for: 30s
        labels:
          issue: "The pod {{ $labels.pod }} in {{ $labels.namespace }} was recently OOMkilled."
          severity: critical
