- name: Restart crowdsec
  ansible.builtin.service:
    name: crowdsec
    state: restarted

- name: Restart crowdsec-firewall-bouncer
  ansible.builtin.service:
    name: crowdsec_firewall_bouncer
    state: restarted
