- name: Install common packages for Debian
  ansible.builtin.apt:
    state: present
    name:
      - neovim
      - htop
      - btop
      - iperf3
      - curl
      - git
      - smartmontools
      - sysstat
  when: ansible_distribution | lower == "debian"

- name: Install common packages for OpenBSD
  ansible.builtin.openbsd_pkg:
    state: present
    name:
      - neovim
      - htop
      - btop
      - iperf3
      - curl
      - ssh-copy-id  # included in default debian install
      - git
  when: ansible_distribution | lower == 'openbsd'

- name: Install common packages for OpenWRT
  community.general.opkg:
    state: present
    name:
      - vim
      - htop
      - btop
      - iperf3
      - curl
      - git
  when: ansible_distribution | lower == 'openwrt'
