- name: "Set net.ipv4.ip_unprivileged_port_start when using podman"
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: 80
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/90-ansible_managed.conf
  when: container_tool == "podman"

- name: "Install and configure traefik"
  ansible.builtin.include_role:
    name: container-app
    public: false
