apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkwarden
  namespace: linkwarden
spec:
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  releaseName: linkwarden
  values:
    controllers:
      main:
        enabled: true
        containers:
          main:
            image:
              repository: ghcr.io/linkwarden/linkwarden
              tag: v2.14.0
            env:
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: linkwarden-secret
                    key: DATABASE_URL
              NEXTAUTH_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: linkwarden-secret
                    key: NEXTAUTH_SECRET
              NEXTAUTH_URL: https://linkwarden.${ROOT_DOMAIN}
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: 3000
    ingress:
      main:
        enabled: true
        hosts:
          - host: linkwarden.${LOCAL_ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: linkwarden
                  port: 3000
          - host: linkwarden.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: linkwarden
                  port: 3000
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: linkwarden
        globalMounts:
          - path: /data/data
            readOnly: false
