- name: Update all packages on the system
  community.general.openbsd_pkg:
    name: '*'
    state: latest

- name: Remove all unused dependencies
  community.general.openbsd_pkg:
    name: '*'
    autoremove: true

- name: Run syspatch
  community.general.syspatch:
  register: syspatch_result

- name: Reboot
  ansible.builtin.reboot:
  when: (syspatch_result.reboot_needed or force_reboot is true)
