- name: Import apt-backports role
  ansible.builtin.import_role:
    name: apt-backports

- name: Install package on Debian
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Install config file
  ansible.builtin.template:
    dest: /etc/default/prometheus-node-exporter
    mode: 0644
    owner: root
    group: root
    src: args.j2
  notify:
   - Run systemctl daemon-reload
   - Restart prometheus-node-exporter (debian)

- name: Create /etc/systemd/system/prometheus-node-exporter.service.d directory
  ansible.builtin.file:
    path: /etc/systemd/system/prometheus-node-exporter.service.d
    state: directory

- name: Install systemd drop-in file
  ansible.builtin.copy:
    dest: /etc/systemd/system/prometheus-node-exporter.service.d/override.conf
    mode: 0644
    owner: root
    group: root
    content: |
      [Unit]
      After=tailscale-online.target
      Requires=tailscale-online.target
  notify:
   - Run systemctl daemon-reload
   - Restart prometheus-node-exporter (debian)
