- name: Install package on OpenBSD
  community.general.openbsd_pkg:
    name: node_exporter
    state: present

- name: Add node_exporter_flags to /etc/rc.conf.local
  ansible.builtin.lineinfile:
    path: /etc/rc.conf.local
    line: "node_exporter_flags={{ node_exporter_args }}"
    owner: root
    group: wheel
    mode: '0644'

- name: Configure service
  ansible.builtin.service:
    name: node_exporter
    enabled: true
    state: started
