apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pb4162-dev
  namespace: traefik
spec:
  secretName: pb4162-dev-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
  - "${ROOT_DOMAIN}"
  - "*.${ROOT_DOMAIN}"
