argument_specs:
  main:
    options:
      nginx_additional_modules:
        type: list
        elements: str
        required: false
        default: []
      nginx_http_configs:
        type: dict
        required: true
      nginx_stream_configs:
        type: dict
        required: false
        default: {}
      nginx_proxy_params_config:
        type: str
        required: false
        default: |
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Scheme $scheme;
          proxy_set_header X-Forwarded-Port $server_port;
