apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  chart:
    spec:
      chart: app-template
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  releaseName: audiobookshelf
  values:
    controllers:
      main:
        enabled: true
        containers:
          main:
            image:
              repository: ghcr.io/advplyr/audiobookshelf
              tag: 2.30.0
            env:
              # TODO: can't use cluster-secrets as it's in another namespace
              TZ: ${TIMEZONE}
              PORT: 13378
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: 13378
            targetPort: 13378
    ingress:
      main:
        enabled: true
        hosts:
          - host: audiobookshelf.${LOCAL_ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: audiobookshelf
                  port: 13378
          - host: audiobookshelf.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: audiobookshelf
                  port: 13378
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        globalMounts:
          - path: /config
            readOnly: false
      media:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: audiobookshelf-media
        globalMounts:
          - path: /media
            readOnly: false
      metadata:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: audiobookshelf-metadata
        globalMounts:
          - path: /metadata
            readOnly: false
