apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      version: 7.0.0
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  releaseName: loki
  valuesFrom:
    - kind: Secret
      name: loki-values
  values:
    deploymentMode: SingleBinary
    monitoring:
      rules:
        enabled: true
        labels:
          release: kube-prometheus-stack
      serviceMonitor:
        enabled: true
        labels:
          release: kube-prometheus-stack
    lokiCanary:
      resources:
        limits:
          memory: 64Mi
    gateway:
      resources:
        limits:
          memory: 32Mi
    singleBinary:
      replicas: 1
      resources:
        limits:
          memory: 1.5Gi
      extraEnv:
        - name: GOMEMLIMIT
          value: 1GiB
      persistence:
        whenScaled: Retain
        whenDeleted: Retain
        enableStatefulSetRecreationForSizeChange: true
    loki:
      runtimeConfig:
        overrides:
          fake:
            deletion_mode: filter-and-delete
      limits_config:
        retention_period: 60d
      compactor:
        retention_enabled: true
        delete_request_store: s3
        retention_delete_delay: 0s
        compaction_interval: 10m
        working_directory: /var/loki/compactor/retention
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      storage:
        bucketNames:
          chunks: loki
          ruler: loki
          admin: loki
        s3:
          endpoint: "http://garage.garage.svc.cluster.local:3900"
          s3ForcePathStyle: true
          region: garage
          accessKeyId: GK759a5cbb96f1b86245c1f656
          insecure: true
      ingester:
        chunk_encoding: snappy
      tracing:
        enabled: true
      querier:
        max_concurrent: 2
    resultsCache:
      allocatedMemory: 128
      writebackSizeLimit: 10MB
    chunksCache:
      allocatedMemory: 128
      writebackSizeLimit: 10MB
    memberlist:
      service:
        publishNotReadyAddresses: true
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0 
