argument_specs:
  main:
    options:
      traefik_dashboard_subdomain:
        type: str
        required: false
        default: traefik
      traefik_static_config:
        type: dict
        required: false
        default: {}
      traefik_static_config_private:
        type: dict
        required: false
        default: {}
      traefik_dynamic_config:
        type: dict
        required: false
        default: {}
      traefik_dynamic_config_private:
        type: dict
        required: false
        default: {}
      traefik_env_vars:
        type: dict
        required: false
        default: {}
      traefik_version:
        type: str
        required: true
