apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: ${JELLYFIN_MEDIA_VOLUME_SIZE}
  storageClassName: truenas-smb
