apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1024Gi
  storageClassName: truenas-smb
