apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chrome
  namespace: karakeep
spec:
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  releaseName: chrome
  values:
    controllers:
      main:
        enabled: true
        containers:
          main:
            image:
              repository: ghcr.io/karakeep-app/karakeep-chrome
              tag: 151.0.7922.47-r1
            command:
              - chromium-browser
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --hide-scrollbars
              - --disable-blink-features=AutomationControlled
              - --window-size=1440,900
    service:
      main:
        enabled: true
        controller: main
        ports:
          tcp:
            enabled: true
            port: 9222
            protocol: TCP
