apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-sidecar-data
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
