- name: "Create config directory"
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: "0755"

- name: "Install config file"
  ansible.builtin.template:
    src: k3s-config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    mode: 0640
  notify: Restart k3s

- name: "Install registry config file"
  ansible.builtin.template:
    src: k3s-registry-config.yaml.j2
    dest: /etc/rancher/k3s/registries.yaml
    mode: 0640
  notify: Restart k3s
