# TODO: review and remove

# - name: "Get k3s version info"
#   ansible.builtin.command: kubectl version -o json
#   register: k3s_version_info
#   changed_when: false
#   failed_when: false
#
# - block:
#   - name: "Set current_k3s_ver"
#     ansible.builtin.set_fact:
#       current_k3s_ver: "{{ (k3s_version_info.stdout | from_json).clientVersion.gitVersion }}"
#   
#   - name: "Check if an update is available"
#     ansible.builtin.set_fact:
#       k3s_is_update: "{{ k3s_version is version(current_k3s_ver, '>') }}"
#   when: k3s_version_info.stdout != ""
#
# - name: "Set k3s_run_install_script"
#   ansible.builtin.set_fact:
#     k3s_run_install_script: "{{ (current_k3s_ver is undefined) or k3s_is_update or (k3s_force_run_install_script | default(false)) }}"
#
