- name: Set release_arch
  ansible.builtin.set_fact:
    release_arch: >-
      {{
        "amd64" if ansible_architecture == "x86_64"
        else "arm64" if ansible_architecture == "aarch64"
      }}
