apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubewall
  namespace: kubewall-system
spec:
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  releaseName: kubewall
  values:
    controllers:
      main:
        enabled: true
        pod:
        containers:
          main:
            image:
              repository: ghcr.io/kubewall/kubewall
              tag: 0.0.17
            args:
              - "--no-open-browser"
              - "--listen=:7080"
              - "--k8s-client-qps=500"
              - "--k8s-client-burst=500"
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            protocol: HTTP
            port: 7080
    ingress:
      main:
        enabled: true
        hosts:
          - host: kubernetes.${LOCAL_ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: kubewall
                  port: 7080
          - host: kubernetes.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: kubewall
                  port: 7080
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /.kubewall
            readOnly: false
    rbac:
      bindings:
        cluster-admin-binding:
          enabled: true
          type: ClusterRoleBinding
          roleRef:
            kind: ClusterRole
            name: cluster-admin
          subjects:
            - kind: ServiceAccount
              name: default
              namespace: kubewall-system
