apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: ${NEXTCLOUD_STORAGE_VOLUME_SIZE}
  storageClassName: truenas-smb-nextcloud
