---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-secrets
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/clusters/homelab/apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name: secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-secrets
    - name: core
  interval: 5m
  path: "./kubernetes/apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  patches:
    - patch: |
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: all
        spec:
          interval: 10m
          timeout: 5m
          driftDetection:
            mode: enabled
            ignore:
            - paths: ["/spec/replicas"]
              target:
                kind: Deployment
      target:
        kind: HelmRelease
    - patch: |
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRepository
        metadata:
          name: all
        spec:
          interval: 5m
      target:
        kind: HelmRepository
    - patch: |
        - op: add
          path: /metadata/labels
          value:
            goldilocks.fairwinds.com/enabled: true
      target:
        kind: Namespace
