---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: private-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: secrets
  interval: 20m
  path: "./kubernetes/apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure-private
  patches:
    # common fields for all namespaces
    - target:
        kind: Namespace
      patch: |
        - op: add
          path: /metadata/labels
          value:
            goldilocks.fairwinds.com/enabled: "true"
        - op: add
          path: /metadata/annotations
          value:
            kustomize.toolkit.fluxcd.io/prune: disabled
    # common fields for all child kustomizations
    - target:
        kind: Kustomization
        group: kustomize.toolkit.fluxcd.io
      patch: |
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: _
        spec:
          interval: 20m
          prune: true
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: cluster-settings
              - kind: Secret
                name: cluster-secrets
          sourceRef:
            kind: GitRepository
            name: infrastructure-private
            namespace: flux-system
          patches:
            # common fields for all helm releases
            - target:
                kind: HelmRelease
                group: helm.toolkit.fluxcd.io
              patch: |
                apiVersion: helm.toolkit.fluxcd.io/v2
                kind: HelmRelease
                metadata:
                  name: all
                spec:
                  interval: 20m
                  timeout: 5m
                  driftDetection:
                    mode: enabled
                    ignore:
                    - paths: ["/spec/replicas"]
                      target:
                        kind: Deployment
                    - paths: ["/spec/replicas"]
                      target:
                        kind: StatefulSet

            # common fields for all helm repositories
            - target:
                kind: HelmRepository
                group: helm.toolkit.fluxcd.io
              patch: |
                apiVersion: helm.toolkit.fluxcd.io/v2
                kind: HelmRepository
                metadata:
                  name: all
                spec:
                  interval: 20m
