argument_specs:
  main:
    options:
      k3s_version:
        type: "str"
        required: true
      k3s_base_config:
        type: "dict"
        required: false
        default: {}
      k3s_base_config_private:
        type: "dict"
        required: false
        default: {}
      k3s_master_config:
        type: "dict"
        required: false
        default: {}
      k3s_master_config_private:
        type: "dict"
        required: false
        default: {}
      k3s_registry_config:
        type: "dict"
        required: false
        default: {}
      k3s_registry_config_private:
        type: "dict"
        required: false
        default: {}
      k3s_update:
        type: "bool"
        required: false
        default: false
