apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: monitoring
spec:
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 11.8.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 5m
  releaseName: prometheus-blackbox-exporter
  values:
    resources:
      limits:
        memory: 128Mi
    config:
      modules:
        http_2xx:
          http:
            tls_config:
              insecure_skip_verify: true
    serviceMonitor:
      selfMonitor:
        enabled: true
        labels:
          release: kube-prometheus-stack
      enabled: true
      defaults:
        labels:
          release: kube-prometheus-stack
      targets:
        - name: pb4162-dev
          url: https://pb4162.dev
          interval: 10s
          scrapeTimeout: 10s
          module: http_2xx
    configReloader:
      enabled: true
