apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  labels:
    release: kube-prometheus-stack
  name: podman-exporter-scrape-config
  namespace: monitoring
spec:
  basicAuth:
    password:
      key: password
      name: podman-exporter-basic-auth
    username:
      key: username
      name: podman-exporter-basic-auth
  jobName: podman-exporter
  metricsPath: /metrics
  scrapeInterval: 20s
  staticConfigs:
  - targets:
    - podman-exporter.podman.${ROOT_DOMAIN}
