- name: Install borgbackup
  ansible.builtin.apt:
    name: borgbackup
    state: present

- name: Configure user account
  ansible.builtin.user:
    name: "{{ borg_server_user }}"
    create_home: true
    shell: /bin/bash
    state: present
  register: borg_user_info

- name: Create ~/.ssh and ~/repos directories
  ansible.builtin.file:
    path: "{{ (borg_server_user_home_dir, item) | path_join }}"
    state: directory
    owner: "{{ borg_user_info.uid }}"
    group: "{{ borg_user_info.group }}"
  loop:
    - ".ssh"
    - "{{ borg_server_mount_dir }}"

- name: Configure smb share for borg repos
  ansible.builtin.import_tasks: smb.yml
  when: borg_server_smb_path is defined

- name: Configure local path for borg repos
  ansible.builtin.import_tasks: local-path.yml
  when: borg_server_local_path is defined
