- name: Do Debian-specific install tasks
  ansible.builtin.import_tasks: install_debian.yml
  when: ansible_distribution | lower == "debian"

- name: Do OpenBSD-specific install tasks
  ansible.builtin.import_tasks: install_openbsd.yml
  when: ansible_distribution | lower == "openbsd"

- name: "Pull updates from crowdsec hub"
  ansible.builtin.shell: cscli hub update
  register: hub_update_info
  changed_when: ("Nothing to do" not in hub_update_info.stdout)
  notify: "Restart crowdsec ({{ ansible_distribution | lower }})"

- name: "Enroll in crowdsec console under name: {{ crowdsec_console_name }}"
  ansible.builtin.shell: >-
    cscli console enroll
    {{ crowdsec_console_key | quote }}
    --name {{ crowdsec_console_name | quote }}
    {% if crowdsec_enrollment_overwrite %}
    --overwrite
    {% endif %}
  register: console_enroll_info
  changed_when: ("Instance already enrolled" not in console_enroll_info.stderr)
  notify: "Restart crowdsec ({{ ansible_distribution | lower }})"

- name: "Register new firewall bouncer on OpenBSD only"
  when: (ansible_distribution | lower == "openbsd")
  block:
  - name: "Create firewall bouncer with cscli"
    ansible.builtin.shell: >-
      cscli bouncers add {{ crowdsec_firewall_bouncer_name | quote }} -o json
    register: crowdsec_firewall_bouncer_add_info
    changed_when: ("already exists" not in crowdsec_firewall_bouncer_add_info.stderr)
    failed_when: crowdsec_firewall_bouncer_add_info.rc not in [0, 1]

  - name: "Get firewall bouncer API key"
    ansible.builtin.set_fact:
      crowdsec_firewall_bouncer_api_key: "{{ crowdsec_firewall_bouncer_add_info.stdout | from_json }}"
    when: |
      ("already exists" not in crowdsec_firewall_bouncer_add_info.stderr
      and crowdsec_firewall_bouncer_api_key is undefined)

  - name: "Set crowdsec_firewall_bouncer_config_path"
    ansible.builtin.set_fact:
      crowdsec_firewall_bouncer_config_path: >-
        {{
          "/etc/crowdsec-firewall-bouncer/crowdsec-firewall-bouncer.yaml" if ansible_distribution | lower == "openbsd"
          else "/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml" if ansible_distribution | lower == "debian"
        }}

  - name: "Replace ${API_KEY} in firewall bouncer config with API key"
    ansible.builtin.replace:
      backup: true
      path: "{{ crowdsec_firewall_bouncer_config_path }}"
      regexp: "\\${API_KEY}"
      replace: "{{ crowdsec_firewall_bouncer_api_key }}"
    notify:
      - "Restart crowdsec-firewall-bouncer ({{ ansible_distribution | lower }})"
      - "Restart crowdsec ({{ ansible_distribution | lower }})"
    when: (crowdsec_firewall_bouncer_api_key is defined)

- name: "Install collections, parsers, etc. from crowdsec hub"
  ansible.builtin.shell: |
    cscli {{ item.type }}s install {{ item.name | quote }}
  register: crowdsec_hub_install_info
  changed_when: >-
    (
      ("Nothing to" not in crowdsec_hub_install_info.stdout)
    )
  loop: "{{ crowdsec_hub_items }}"
  notify: "Restart crowdsec ({{ ansible_distribution | lower }})"

- name: "Install acquisitions"
  ansible.builtin.copy:
    backup: true
    content: "{{ item.value | to_nice_yaml }}"
    dest: "/etc/crowdsec/acquis.d/{{ item.key }}.yaml"
  loop: "{{ crowdsec_acquisitions | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  notify: "Restart crowdsec ({{ ansible_distribution | lower }})"
