- name: "apt: Install open-iscsi, nfs-common, cryptsetup and dmsetup"
  ansible.builtin.apt:
    state: present
    name:
      - open-iscsi
      - nfs-common
      - cryptsetup
      - dmsetup

- name: "Load dm_crypt kernel module"
  community.general.modprobe:
    name: dm_crypt
    persistent: present
    state: present
