kind: Kustomization
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/homelab/cluster-secrets.yaml"
  prune: true
  sourceRef:
    kind: GitRepository
    name: secrets
  decryption:
    provider: sops
    encrypted_regex: ^(data|stringData)$
    secretRef:
      name: sops-age
