- name: "Download install script"
  ansible.builtin.get_url:
    url: https://tailscale.com/install.sh
    dest: "~/install_tailscale.sh"
    mode: a+x

- name: "Run install script"
  ansible.builtin.shell: ~/install_tailscale.sh >> ~/tailscale_install_log.txt
  args:
    chdir: "~"
    creates: /usr/bin/tailscale

- name: "Enable and start tailscaled"
  ansible.builtin.systemd_service:
    name: tailscaled.service
    state: started
    enabled: true
