- name: "Install tailscale"
  community.general.apk:
    state: present
    name: tailscale

- name: "Enable and start tailscale"
  community.general.openwrt_init:
    name: tailscale
    enabled: true
    state: started
