argument_specs:
  main:
    options:
      gatus_env:
        type: dict
        required: false
        default: {}
      gatus_version:
        type: str
        required: true
      gatus_port:
        type: int
        required: false
        default: 8080
      gatus_config:
        type: dict
        required: true
      gatus_endpoints:
        type: dict
        required: true
