[k8s_control_node]
raspberrypi5 ansible_user=pi

[pis]
raspberrypi5
raspberrypi5-2
raspberrypi5-3

[pis:vars]
ansible_user=pi

[mini_pcs]
nucbox-m3
nucbox-m3-2
nucbox-m3-3

[mini_pcs:vars]
ansible_user=pb

[k8s_nodes]
raspberrypi5-2 ansible_user=pi
raspberrypi5-3 ansible_user=pi

[k8s_nodes:children]
mini_pcs

[k8s_cluster:children]
k8s_nodes
k8s_control_node

[openbsd_vps]
openbsdvps

[openbsd_vps:vars]
ansible_user=pb
ansible_python_interpreter=/usr/local/bin/python3
ansible_become_method=doas
