apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  LOCAL_ROOT_DOMAIN: "cluster.internal"
  ROOT_DOMAIN: "pb4162.dev"
  JELLYFIN_MEDIA_VOLUME_SIZE: "1536Gi"
  NEXTCLOUD_STORAGE_VOLUME_SIZE: "1024Gi"
  # renovate: datasource=docker depName=ghcr.io/tensorchord/cloudnative-vectorchord
  CNPG_IMMICH_CONTAINER_VERSION: 16.9-0.4.3
