apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  LOCAL_ROOT_DOMAIN: "cluster.local"
  ROOT_DOMAIN: "pb4162.dev"
  JELLYFIN_MEDIA_VOLUME_SIZE: "1536Gi"
  NEXTCLOUD_STORAGE_VOLUME_SIZE: "1024Gi"
