apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-app-ini
  namespace: gitea
data:
  service: |
    DISABLE_REGISTRATION=true
  repository: |
    ENABLE_PUSH_CREATE_USER=true
  actions: |
    ENABLED=true
