when:
  - event: push
    branch: main
    path: 'ansible/*'
  - event: manual


clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 0
      partial: false


steps:
  - name: Pull repo with ansible_cd python script
    image: alpine/git:v2.54.0
    commands:
      - git clone https://github.com/pb4162/infrastructure.git script_home

  - name: Run ansible_cd python script
    image: python:3.14.7
    environment:
      SEMAPHOREUI_KEY:
        from_secret: semaphoreui_key
      SEMAPHOREUI_HOST:
        from_secret: semaphoreui_host
      SEMAPHOREUI_PROJECT_ID:
        from_secret: semaphoreui_project_id
      SEMAPHOREUI_TASK_TEMPLATE_ID:
        from_secret: semaphoreui_task_template_id
    commands:
      - pip install requests
      - git config --global --add safe.directory '.'
      - python script_home/scripts/ansible_cd.py
