---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: jellyfin-media-smb
spec:
  capacity:
    storage: ${JELLYFIN_MEDIA_VOLUME_SIZE}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0770
    - file_mode=0770
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "//${TRUENAS_URL}/jellyfin##"
    volumeAttributes:
      source: "//${TRUENAS_URL}/jellyfin"
    nodeStageSecretRef:
      name: smbcreds
      namespace: kube-system
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-media-smb
  namespace: navidrome
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${JELLYFIN_MEDIA_VOLUME_SIZE}
  volumeName: "jellyfin-media-smb"
  storageClassName: smb
