- name: "systemd: Disable and stop dphys-swapfile.service"
  ansible.builtin.systemd_service:
    name: dphys-swapfile.service
    enabled: false
    state: stopped
  when: ("pis" in group_names)
  notify: Reboot

- name: "systemd: Mask swap service"
  ansible.builtin.systemd_service:
    name: "{{ hostvars[ansible_host]['swap_path'] }}"
    masked: yes
  when: ("mini_pcs" in group_names)
  notify: Reboot

