argument_specs:
  main:
    options:
      container_tool:
        type: str
        required: false
        default: docker
      container_data_dir:
        type: str
        required: true
      app_name:
        type: str
        required: true
      app_directories:
        type: list
        required: false
        default: []
      app_templates:
        type: list
        elements: dict
        required: false
        default: []
      app_networks:
        type: list
        elements: str
        required: false
        default: []
      app_systemd_requires:
        type: list
        elements: str
        required: false
        default: []
      app_systemd_after:
        type: list
        elements: str
        required: false
        default: []
