apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-device-plugin
  namespace: kube-system
spec:
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.34.0
      sourceRef:
        kind: HelmRepository
        name: intel
      interval: 5m
  releaseName: gpu-device-plugin
  upgrade:
    crds: CreateReplace
  dependsOn:
    - name: device-plugin-operator
  values:
    sharedDevNum: 20
