technitium_env_base:
  DNS_SERVER_DOMAIN: dns-server #The primary domain name used by this DNS Server to identify itself.
  DNS_SERVER_WEB_SERVICE_HTTP_PORT: "5380" #The TCP port number for the DNS web console over HTTP protocol.
  DNS_SERVER_LOG_USING_LOCAL_TIME: "true" #Enable this option to use local time instead of UTC for logging.
  DNS_SERVER_LOG_FOLDER_PATH: /var/log/technitium/dns #The folder path on the server where the log files should be saved.
  DNS_SERVER_LOG_MAX_LOG_FILE_DAYS: "365" #Max number of days to keep the log files. Log files older than the specified number of days will be deleted automatically. Set 0 to disable auto delete.
  DNS_SERVER_STATS_MAX_STAT_FILE_DAYS: "365" #Max number of days to keep the dashboard stats. Stat files older than the specified number of days will be deleted automatically. Set 0 to disable auto delete.
