- name: "Restart k3s (master)"
  ansible.builtin.systemd_service:
    name: k3s.service
    state: restarted

- name: "Restart k3s (worker)"
  ansible.builtin.systemd_service:
    name: k3s-agent.service
    state: restarted
